sudo: required
services:
  - docker

before_install:
  - docker build -t tranng/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tranng/react-test npm test -- --coverage

after_success:
  - docker build -t tranng/multi-client ./client
  - docker build -t tranng/multi-nginx ./nginx
  - docker build -t tranng/multi-server ./server
  - docker build -t tranng/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tranng/multi-client
  - docker push tranng/multi-nginx
  - docker push tranng/multi-server
  - docker push tranng/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: Multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-529154268433
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY